http:
  ip: 0.0.0.0
  port: 8100

tnt:
  ip: 127.0.0.1
  port: 3333

provider:
  ropsten: https://ropsten.infura.io:443/Hn1kZjKCMl14LtX3tfIy
  kovan: https://ropsten.infura.io:443/Hn1kZjKCMl14LtX3tfIy
  rinkeby: https://ropsten.infura.io:443/Hn1kZjKCMl14LtX3tfIy
  mainnet: https://mainnet.infura.io:443/Hn1kZjKCMl14LtX3tfIy
